### ISSUE TITLE
Line 1967: Image.bandNames: Parameter 'image' is required.

### ISSUE THREAD

**Issue by Amaralowsky** [jmlea16/GEECE#1]
I'm using the HadGEM3-GC31-MM.

**Comment by jmlea16** [comment]
Hi, can you confirm which settings you were using on the main panel so I can try to reproduce the error?
Cheers,
James

**Comment by Amaralowsky** [comment]
Sure, this error occurred to me using different simulation scenarios; Using the HadGEM3-GC31-MM model; Precipitation Variable; Extract individual model simulation results; Start/End Dates by default; Temporal Resolution: Annual; Export in GeoTiff format with the following coordinates:

Latitude: -35.420158988732446, -25.199712676765515, -25.199712676765515, -35.420158988732446
Longitude: -48.79673342424118, -48.79673342424118, -59.51938967424118, -59.51938967424118

Thank you for your availability and attention!! Greetings from the south of Brazil!

**Comment by jmlea16** [comment]
Found the issue! There was a rogue data free band lurking in the image collection for export. I've tested the fix using your inputs above and the data successfully exported. If you could confirm whether it is now working using the updated code (link below) then will mark the issue closed :)

Thanks again for flagging this, and greetings from Liverpool!

https://code.earthengine.google.com/7667d958c2c70b9be5e6f1210da50465
